<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--<TargetFramework>net8.0</TargetFramework>-->
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!--<Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.Library.Sdk" Version="2.0.0" />

  <PropertyGroup>
    <Title>Lombiq Helpful Libraries - Common Libraries</Title>
    <CopyrightYear>2011</CopyrightYear>
    <DescriptionBody>Various useful libraries that can be handy when developing for .NET. See the project website for detailed documentation.</DescriptionBody>
    <PackageTags>Lombiq;DateTime;DependencyInjection;Utilities</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.Common/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>

    <!--<PackageReference Include="Microsoft.Extensions.Caching.Memory" />-->
    <!--<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />-->
    <!--<PackageReference Include="System.Linq.Async"  />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GuangCore\GuangCore.TopRef\GuangCore.TopRef.csproj" />

  </ItemGroup>

  <!--<Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.21.osoe-925" />-->
</Project>
