<Project>
  <PropertyGroup>
    <!--<TargetFramework>net8.0</TargetFramework>-->
    <Nullable>enable</Nullable>
  </PropertyGroup>



  <PropertyGroup>
    <Title>Lombiq Helpful Libraries</Title>
    <CopyrightYear>2011</CopyrightYear>
    <DescriptionBody>Various useful libraries that can be handy when developing for .NET, ASP.NET Core, and Orchard Core, to be used from your own projects. This package references all Helpful Libraries libraries, but you can use only the ones specific for your use-case, see the dependencies. See the project website for detailed documentation.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;YesSql;DateTime;DependencyInjection;GraphQL;Liquid;Localization;Middlewares;Utilities;LinqToDB</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.Attributes\Lombiq.HelpfulLibraries.Attributes.csproj"  />
   
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.AspNetCore\Lombiq.HelpfulLibraries.AspNetCore.csproj"  />
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.Common\Lombiq.HelpfulLibraries.Common.csproj"  />
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj"  />
    <ProjectReference Include="..\Lombiq.HelpfulLibraries.LinqToDb\Lombiq.HelpfulLibraries.LinqToDb.csproj"  />
  </ItemGroup>

   
</Project>
