<Project>
  <PropertyGroup>
    <!--<TargetFramework>net8.0</TargetFramework>-->
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <

  <PropertyGroup>
    <Title>Lombiq Helpful Libraries - LINQ to DB Libraries for Orchard Core</Title>
    <CopyrightYear>2011</CopyrightYear>
    <DescriptionBody>With the help of this project you can write LINQ expressions and run them with a YesSql ISession extension method to query from the DB instead of writing plain SQL queries. Uses the LINQ to DB project. See the project website for detailed documentation.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;YesSql;linq2db;LinqToDB</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.LinqToDb/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="linq2db" />
    <!--<PackageReference Include="OrchardCore.Data.YesSql" Version="2.1.0" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GuangCore\GuangCore.TopRef\GuangCore.TopRef.csproj" />

  </ItemGroup>

 
</Project>
