<Project>
    <PropertyGroup>
      <!--<TargetFramework>netstandard2.0</TargetFramework>-->
      <IsPackable>true</IsPackable>
      <Nullable>enable</Nullable>
      <LangVersion>14.0</LangVersion>
    </PropertyGroup>

   

    <PropertyGroup>
        <Title>Lombiq Helpful Libraries - Attributes for Orchard Core</Title>
        <CopyrightYear>2011</CopyrightYear>
        <DescriptionBody>Adds attributes used by other projects. See the project website for detailed documentation.</DescriptionBody>
        <PackageTags>OrchardCore;Lombiq;Attributes</PackageTags>
        <RepositoryUrl>https://github.com/Lombiq/Helpful-Libraries</RepositoryUrl>
        <PackageProjectUrl>https://github.com/Lombiq/Helpful-Libraries/blob/dev/Lombiq.HelpfulLibraries.Attributes/Readme.md</PackageProjectUrl>
    </PropertyGroup>

  
</Project>
